version: '3.8'

services:
  # Base de datos PostgreSQL para notification service
  notification-postgres:
    image: postgres:15-alpine
    container_name: notification-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: noti_user
      POSTGRES_PASSWORD: noti_pass
      POSTGRES_DB: notification_db
    ports:
      - "5433:5432"  # Puerto diferente para no conflictuar
    volumes:
      - notification-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U noti_user -d notification_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - notification-network

  # RabbitMQ para desarrollo local
  rabbitmq-local:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq-local
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq-local-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - notification-network

  # Notification Service
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-service-local
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8083
      - JWT_SECRET=test-secret-key-for-jwt-validation-minimum-256-bits-long
      - SPRING_DATASOURCE_URL=jdbc:postgresql://notification-postgres:5432/notification_db
      - SPRING_DATASOURCE_USERNAME=noti_user
      - SPRING_DATASOURCE_PASSWORD=noti_pass
      - SPRING_RABBITMQ_HOST=rabbitmq-local
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      # Configuración SMTP (usando Mailtrap o similar para desarrollo)
      - SPRING_MAIL_HOST=${SMTP_HOST:-smtp.mailtrap.io}
      - SPRING_MAIL_PORT=${SMTP_PORT:-2525}
      - SPRING_MAIL_USERNAME=${SMTP_USERNAME:-your-username}
      - SPRING_MAIL_PASSWORD=${SMTP_PASSWORD:-your-password}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
    depends_on:
      notification-postgres:
        condition: service_healthy
      rabbitmq-local:
        condition: service_healthy
    networks:
      - notification-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  notification-network:
    driver: bridge

volumes:
  notification-db-data:
    driver: local
  rabbitmq-local-data:
    driver: local